# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80276d2a13643f3c68274613ced78a7819a4c17b5686afdb33f0761f9c0204706977cd0d592c224e07b3a047c23e33c9a4b8e2960f1cea98324eed5a39d39392

test:
  secret_key_base: 1c8ccdae6e96ec1a8ad5fd93ce699a376d48828aab70d21346c2d16c5d515476df9f606f7d7c779750ba0b095b8bb00d3498cdecd2074f4e918a26a7cf6bcaa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
